[LOOTS]
	#Should coins be lootable from chests
	coinsLootChests = false

[COINS_SILVER]
	#The value of a silver coin
	#WARNING: When considering an economic system that operates only with integers, values are automatically rounded up. For example, a value of 1.5 is treated as 2.
	# Default: 1.0
	# Range: 0.01 ~ 1000000.0
	silverMagicValue = 1.0

[COINS_GOLD]
	#The value of a gold coin
	#WARNING: When considering an economic system that operates only with integers, values are automatically rounded up. For example, a value of 1.5 is treated as 2.
	# Default: 50.0
	# Range: 0.01 ~ 1000000.0
	goldMagicValue = 50.0

[COINS_CRYSTAL]
	#The value of a crystal coin
	#WARNING: When considering an economic system that operates only with integers, values are automatically rounded up. For example, a value of 1.5 is treated as 2.
	# Default: 2500.0
	# Range: 0.01 ~ 1000000.0
	crystalMagicValue = 2500.0
