[COLLECT_COINS_BUTTON]
	#X position for coin button
	#Tips: 80 for align for right side
	# Default: 0
	# Range: > -2147483648
	xCollectCoins = 0
	#Y position for coin button
	# Default: 0
	# Range: > -2147483648
	yCollectCoins = 0
	#Enable convert buttons on collect coins button
	enableConvertButtons = true

[SILVER_BUTTON]
	#Enable silver button
	enableSilverButton = true
	#X position of silver button
	# Default: 0
	# Range: -750 ~ 750
	xSilverButton = 0
	#Y position of silver button
	# Default: 0
	# Range: -750 ~ 750
	ySilverButton = 0

[GOLD_BUTTON]
	#Enable gold button
	enableGoldButton = true
	#X position of gold button
	# Default: 0
	# Range: -750 ~ 750
	xGoldButton = 0
	#Y position of gold button
	# Default: 0
	# Range: -750 ~ 750
	yGoldButton = 0

[CRYSTAL_BUTTON]
	#Enable crystal button
	enableCrystalButton = true
	#X position of crystal button
	# Default: 0
	# Range: -750 ~ 750
	xCrystalButton = 0
	#Y position of crystal button
	# Default: 0
	# Range: -750 ~ 750
	yCrystalButton = 0

[SILVER_FOR_GOLD_BUTTON]
	#Enable silver-for-gold button
	enableSilverForGoldButton = false
	#X position
	# Default: 0
	# Range: -750 ~ 750
	xSilverForGoldButton = 0
	#Y position
	# Default: 0
	# Range: -750 ~ 750
	ySilverForGoldButton = 0

[GOLD_FOR_SILVER_BUTTON]
	#Enable gold-for-silver button
	enableGoldForSilverButton = false
	#X position
	# Default: 0
	# Range: -750 ~ 750
	xGoldForSilverButton = 0
	#Y position
	# Default: 0
	# Range: -750 ~ 750
	yGoldForSilverButton = 0

[GOLD_FOR_CRYSTAL_BUTTON]
	#Enable gold-for-crystal button
	enableGoldForCrystalButton = false
	#X position
	# Default: 0
	# Range: -750 ~ 750
	xGoldForCrystalButton = 0
	#Y position
	# Default: 0
	# Range: -750 ~ 750
	yGoldForCrystalButton = 0

[CRYSTAL_FOR_GOLD_BUTTON]
	#Enable crystal-for-gold button
	enableCrystalForGoldButton = false
	#X position
	# Default: 0
	# Range: -750 ~ 750
	xCrystalForGoldButton = 0
	#Y position
	# Default: 0
	# Range: -750 ~ 750
	yCrystalForGoldButton = 0
