[DISPLAYS]
	#The x position of the display for coins
	#Tips: 80 for align for right side
	# Default: 0
	# Range: > -2147483648
	xDisplayCurrency = 0
	#The y position of the display for coins
	# Default: 0
	# Range: > -2147483648
	yDisplayCurrency = 0
	#Whether to display the coin amount in the inventory screen
	activeDisplayCurrency = true
	#Type of currency display: "default" or "magic_coins"
	typeDisplayCurrency = "magic_coins"
