["Spring to Life"]
	#allow falling leaves particles to generate
	falling_leaves = true
	#how often should falling leaves particles generate
	# Default: 0.01
	# Range: 0.0 ~ 1.0
	falling_leaves_frequency = 0.01
	#Use the legacy spawn egg textures
	use_legacy_spawn_eggs = false
